# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'top.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TopWindow(object):
    def setupUi(self, TopWindow):
        TopWindow.setObjectName("TopWindow")
        TopWindow.resize(800, 478)
        self.centralwidget = QtWidgets.QWidget(TopWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_setting = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_setting.setGeometry(QtCore.QRect(10, 10, 251, 131))
        self.pushButton_setting.setMouseTracking(False)
        self.pushButton_setting.setCheckable(False)
        self.pushButton_setting.setObjectName("pushButton_setting")
        self.pushButton_mdcn_info = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_mdcn_info.setGeometry(QtCore.QRect(10, 290, 350, 130))
        self.pushButton_mdcn_info.setObjectName("pushButton_mdcn_info")
        self.pushButton_record = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_record.setGeometry(QtCore.QRect(400, 290, 350, 130))
        self.pushButton_record.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_record.setObjectName("pushButton_record")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(290, 10, 461, 121))
        self.textBrowser.setObjectName("textBrowser")
        TopWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TopWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        TopWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TopWindow)
        self.statusbar.setObjectName("statusbar")
        TopWindow.setStatusBar(self.statusbar)

        self.retranslateUi(TopWindow)
        self.pushButton_setting.pressed.connect(TopWindow.pressed_setting)
        self.pushButton_mdcn_info.pressed.connect(TopWindow.pressed_mdcn_info)
        self.pushButton_record.pressed.connect(TopWindow.pressed_mdcn_record)
        QtCore.QMetaObject.connectSlotsByName(TopWindow)

    def retranslateUi(self, TopWindow):
        _translate = QtCore.QCoreApplication.translate
        TopWindow.setWindowTitle(_translate("TopWindow", "TopWindow"))
        self.pushButton_setting.setText(_translate("TopWindow", "設定"))
        self.pushButton_mdcn_info.setText(_translate("TopWindow", "お薬情報"))
        self.pushButton_record.setText(_translate("TopWindow", "服薬記録"))
        self.textBrowser.setHtml(_translate("TopWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:72pt; font-style:italic;\">おくすり奉行</span></p></body></html>"))
