# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 320)
        self.pushButton_return = QtWidgets.QPushButton(Form)
        self.pushButton_return.setGeometry(QtCore.QRect(10, 10, 121, 71))
        self.pushButton_return.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/capsule_return.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_return.setIcon(icon)
        self.pushButton_return.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_return.setFlat(True)
        self.pushButton_return.setObjectName("pushButton_return")
        self.pushButton_setadress = QtWidgets.QPushButton(Form)
        self.pushButton_setadress.setGeometry(QtCore.QRect(150, 10, 311, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_setadress.setFont(font)
        self.pushButton_setadress.setObjectName("pushButton_setadress")
        self.pushButton_set_mealtime = QtWidgets.QPushButton(Form)
        self.pushButton_set_mealtime.setGeometry(QtCore.QRect(20, 100, 261, 201))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.pushButton_set_mealtime.setFont(font)
        self.pushButton_set_mealtime.setObjectName("pushButton_set_mealtime")
        self.pushButton_set_volume = QtWidgets.QPushButton(Form)
        self.pushButton_set_volume.setGeometry(QtCore.QRect(310, 100, 151, 201))
        font = QtGui.QFont()
        font.setFamily("Apple SD Gothic Neo")
        font.setPointSize(30)
        font.setKerning(True)
        self.pushButton_set_volume.setFont(font)
        self.pushButton_set_volume.setObjectName("pushButton_set_volume")

        self.retranslateUi(Form)
        self.pushButton_setadress.pressed.connect(Form.set_adress)
        self.pushButton_return.pressed.connect(Form.return_top)
        self.pushButton_set_mealtime.pressed.connect(Form.set_mealtime)
        self.pushButton_set_volume.pressed.connect(Form.set_volume)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_setadress.setText(_translate("Form", "連絡先設定"))
        self.pushButton_set_mealtime.setText(_translate("Form", "お食事時間設定"))
        self.pushButton_set_volume.setText(_translate("Form", "音量設定"))
